version: '3'
services:
  reactjs:
    container_name: store_reactjs
    build: ./client/
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client/:/home/app
      - /home/app/node_modules
      - /home/app/build
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: /home/app/entrypoint.sh ${ENV} ${CLIENT_PORT}
  nodejs:
    container_name: store_nodejs
    build: ./server/
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server/:/home/app
      - /home/app/node_modules
    env_file:
      - .env
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - WAIT_HOSTS=mongodb:${MONGO_PORT}
      - CHOKIDAR_USEPOLLING=true
  mongodb:
    container_name: store_mongodb
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:  
      - './data:/data/db'
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}