version: '3'
services:
  reactjs:
    container_name: store_reactjs
    build: ./client/
    ports:
     - "3000:3000"
    volumes:
      - ./client/:/home/app
      - /home/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true