version: '3'
services:
  reactjs:
    container_name: store_reactjs
    build: ./client/
    ports:
     - "${PORT}:${PORT}"
    volumes:
      - ./client/:/home/app
      - /home/app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: /home/app/entrypoint.sh ${ENV}